name: si_perisai
description: "Microsleep detection with AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  camera: 0.11.0+1
  flutter:
    sdk: flutter
  flutter_ringtone_player: 4.0.0+3
  google_mlkit_face_detection: 0.8.0
  introduction_screen: 3.1.14
  shared_preferences: 2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app-logo.png"
  min_sdk_android: 21
